<?php
/**
 * Advanced Custom Fields Plugin functionality.
 *
 * @package      BrubakerDesignServices\EvangelistsCRM
 * @author       Dan Brubaker
 * @since        1.0.0
 **/

// add_action( 'acf/init', 'ecrm_acf_init' );
/**
 * Add Google Maps API Key. - NOT USING RIGHT NOW.
 *
 * @return void
 */
function ecrm_acf_init() {
	acf_update_setting( 'google_api_key', 'ADD KEY HERE' );
}

add_filter( 'acf/fields/post_object/result/name=organization', 'ecrm_change_organization_term_results', 10, 4 );
add_filter( 'acf/fields/post_object/result/name=event_organization', 'ecrm_change_organization_term_results', 10, 4 );
/**
 * Adds the City and State to the "Organization" field search results in the Contacts admin
 *
 * @return $title
 */
function ecrm_change_organization_term_results( $title, $post, $field, $post_id ) {

	$address = ecrm_get_short_address( get_field( 'physical_address', $post->ID ), false );

	$title = sprintf(
		'%s – %s',
		$title,
		$address
	);

	return $title;
}

add_filter( 'acf/fields/post_object/result/name=primary_organization_contact', 'ecrm_change_primary_organization_contact_term_results', 10, 4 );
add_filter( 'acf/fields/post_object/result/name=name', 'ecrm_change_primary_organization_contact_term_results', 10, 4 );
add_filter( 'acf/fields/post_object/result/name=primary_event_contact', 'ecrm_change_primary_organization_contact_term_results', 10, 4 );
add_filter( 'acf/fields/post_object/result/name=communication_contact', 'ecrm_change_primary_organization_contact_term_results', 10, 4 );
/**
 * Adds the Prefix, City, and State / Country to the "Primary Contact" field search results in the Organizations admin
 *
 * @return $title
 */
function ecrm_change_primary_organization_contact_term_results( $title, $post, $field, $post_id ) {

	$categories = ecrm_get_terms_list( $post, 'contact_category', ' / ', 1 );
	$address    = ecrm_get_short_address( get_field( 'physical_address', $post->ID ), false );

	$title = sprintf(
		'%s %s – %s',
		$categories,
		$title,
		$address
	);

	return $title;
}

/**
 * Adds Local ACF Fields. To import fields into the GUI, use the .json found in the Assets folder.
 */
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c6e1493a12b0',
			'title'                 => 'Communication Details',
			'fields'                => array(
				array(
					'key'               => 'field_5c6e16c9825ba',
					'label'             => '',
					'name'              => 'communication_group',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '40',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c6e14ff806ea',
							'label'             => 'Contact',
							'name'              => 'communication_contact',
							'type'              => 'post_object',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '100',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'contact',
							),
							'taxonomy'          => '',
							'allow_null'        => 0,
							'multiple'          => 0,
							'return_format'     => 'id',
							'ui'                => 1,
						),
						array(
							'key'               => 'field_5c6e14ba806e9',
							'label'             => 'Date',
							'name'              => 'communication_date',
							'type'              => 'date_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '40',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'F j, Y',
							'return_format'     => 'F j, Y',
							'first_day'         => 0,
						),
						array(
							'key'               => 'field_5c6e1543806eb',
							'label'             => 'Type',
							'name'              => 'communication_type',
							'type'              => 'radio',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '60',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'phone'     => 'Phone',
								'email'     => 'Email',
								'letter'    => 'Letter',
								'thank_you' => 'Thank You Note',
								'in_person' => 'In Person',
							),
							'allow_null'        => 0,
							'other_choice'      => 1,
							'save_other_choice' => 0,
							'default_value'     => '',
							'layout'            => 'vertical',
							'return_format'     => 'value',
						),
					),
				),
				array(
					'key'               => 'field_5c6e15ee806ec',
					'label'             => 'Notes',
					'name'              => 'communication_notes',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '60',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'visual',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'communication',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c6b361fc5fcb',
			'title'                 => 'Contact Summary',
			'fields'                => array(
				array(
					'key'               => 'field_5c6b36fc018a3',
					'label'             => 'Organization',
					'name'              => 'organization',
					'type'              => 'post_object',
					'instructions'      => 'Select an organization for this contact',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '30',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'organization',
					),
					'taxonomy'          => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'return_format'     => 'object',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_5c6b3712018a4',
					'label'             => 'Quick Actions',
					'name'              => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '70',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'new_lines'         => '',
					'esc_html'          => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'contact',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c6d96a0c1fbd',
			'title'                 => 'Event Summary',
			'fields'                => array(
				array(
					'key'               => 'field_5c7ae41319304',
					'label'             => '',
					'name'              => 'event_dates',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '30',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c7adfca305e1',
							'label'             => 'Start Date',
							'name'              => 'start_date',
							'type'              => 'date_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'F j, Y',
							'return_format'     => 'Ymd',
							'first_day'         => 0,
						),
						array(
							'key'               => 'field_5c7ae01d305e2',
							'label'             => 'End Date',
							'name'              => 'end_date',
							'type'              => 'date_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'F j, Y',
							'return_format'     => 'Ymd',
							'first_day'         => 0,
						),
					),
				),
				array(
					'key'               => 'field_5c6fe0d46ec45',
					'label'             => 'Quick Actions',
					'name'              => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '70',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'new_lines'         => '',
					'esc_html'          => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'event',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'discussion',
				3 => 'comments',
			),
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c6b34fa12f4f',
			'title'                 => 'Organization Summary',
			'fields'                => array(
				array(
					'key'               => 'field_5c6b29ef6e6fc',
					'label'             => 'Primary Contact',
					'name'              => 'primary_organization_contact',
					'type'              => 'post_object',
					'instructions'      => 'Select a primary contact for this organization',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '30',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'contact',
					),
					'taxonomy'          => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'return_format'     => 'object',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_5c6b29ef6e70d',
					'label'             => 'Quick Actions',
					'name'              => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '70',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'new_lines'         => '',
					'esc_html'          => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'organization',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c6aebcc897a1',
			'title'                 => 'Contact Details',
			'fields'                => array(
				array(
					'key'               => 'field_5c6b42974b438',
					'label'             => 'General',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5c6aebcc8b640',
					'label'             => 'Preferred Phone',
					'name'              => 'preferred_phone',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5c6aebcc8b659',
					'label'             => 'Secondary Phone',
					'name'              => 'secondary_phone',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5c6aebcc8b64f',
					'label'             => 'Preferred Email',
					'name'              => 'preferred_email',
					'type'              => 'email',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_5c6aebcc8b65f',
					'label'             => 'Is this contact outside of the United States?',
					'name'              => 'international_address_question',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'no'  => 'No',
						'yes' => 'Yes',
					),
					'allow_null'        => 0,
					'other_choice'      => 0,
					'default_value'     => 'no',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key'               => 'field_5c6aebcc8b66c',
					'label'             => 'Physical Address',
					'name'              => 'physical_address',
					'type'              => 'group',
					'instructions'      => 'Add this contact\'s home address here',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c6aebcc92263',
							'label'             => 'Street',
							'name'              => 'street',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6aebcc9227c',
							'label'             => 'City',
							'name'              => 'city',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '40',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6aebcc92291',
							'label'             => 'State',
							'name'              => 'state',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6aebcc8b65f',
										'operator' => '==',
										'value'    => 'no',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'AL' => 'AL – Alabama',
								'AK' => 'AK – Alaska',
								'AZ' => 'AZ – Arizona',
								'AR' => 'AR – Arkansas',
								'CA' => 'CA – California',
								'CO' => 'CO – Colorado',
								'CT' => 'CT – Connecticut',
								'DE' => 'DE – Delaware',
								'FL' => 'FL – Florida',
								'GA' => 'GA – Georgia',
								'HI' => 'HI – Hawaii',
								'ID' => 'ID – Idaho',
								'IL' => 'IL – Illinois',
								'IN' => 'IN – Indiana',
								'IA' => 'IA – Iowa',
								'KS' => 'KS – Kansas',
								'KY' => 'KY – Kentucky',
								'LA' => 'LA – Louisiana',
								'ME' => 'ME – Maine',
								'MD' => 'MD – Maryland',
								'MA' => 'MA – Massachusetts',
								'MI' => 'MI – Michigan',
								'MN' => 'MN – Minnesota',
								'MS' => 'MS – Mississippi',
								'MO' => 'MO – Missouri',
								'MT' => 'MT – Montana',
								'NE' => 'NE – Nebraska',
								'NV' => 'NV – Nevada',
								'NH' => 'NH – New Hampshire',
								'NJ' => 'NJ – New Jersey',
								'NM' => 'NM – New Mexico',
								'NY' => 'NY – New York',
								'NC' => 'NC – North Carolina',
								'ND' => 'ND – North Dakota',
								'OH' => 'OH – Ohio',
								'OK' => 'OK – Oklahoma',
								'OR' => 'OR – Oregon',
								'PA' => 'PA – Pennsylvania',
								'RI' => 'RI – Rhode Island',
								'SC' => 'SC – South Carolina',
								'SD' => 'SD – South Dakota',
								'TN' => 'TN – Tennessee',
								'TX' => 'TX – Texas',
								'UT' => 'UT – Utah',
								'VT' => 'VT – Vermont',
								'VA' => 'VA – Virginia',
								'WA' => 'WA – Washington',
								'WV' => 'WV – West Virginia',
								'WI' => 'WI – Wisconsin',
								'WY' => 'WY – Wyoming',
							),
							'default_value'     => array(),
							'allow_null'        => 1,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_5c6aebcc92298',
							'label'             => 'State / Province',
							'name'              => 'state_province',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6aebcc8b65f',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6aebcc9229e',
							'label'             => 'Zip Code',
							'name'              => 'zip_code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '25',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6aebcc922a5',
							'label'             => 'Country',
							'name'              => 'country',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6aebcc8b65f',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5c6b43d523482',
					'label'             => 'Mailing Address',
					'name'              => 'mailing_address',
					'type'              => 'group',
					'instructions'      => 'Add this contact\'s home mailing address here',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c6b43d523483',
							'label'             => 'Street',
							'name'              => 'street',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '100',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b43d523484',
							'label'             => 'City',
							'name'              => 'city',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '40',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b43d523485',
							'label'             => 'State',
							'name'              => 'state',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6aebcc8b65f',
										'operator' => '==',
										'value'    => 'no',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'AL' => 'AL – Alabama',
								'AK' => 'AK – Alaska',
								'AZ' => 'AZ – Arizona',
								'AR' => 'AR – Arkansas',
								'CA' => 'CA – California',
								'CO' => 'CO – Colorado',
								'CT' => 'CT – Connecticut',
								'DE' => 'DE – Delaware',
								'FL' => 'FL – Florida',
								'GA' => 'GA – Georgia',
								'HI' => 'HI – Hawaii',
								'ID' => 'ID – Idaho',
								'IL' => 'IL – Illinois',
								'IN' => 'IN – Indiana',
								'IA' => 'IA – Iowa',
								'KS' => 'KS – Kansas',
								'KY' => 'KY – Kentucky',
								'LA' => 'LA – Louisiana',
								'ME' => 'ME – Maine',
								'MD' => 'MD – Maryland',
								'MA' => 'MA – Massachusetts',
								'MI' => 'MI – Michigan',
								'MN' => 'MN – Minnesota',
								'MS' => 'MS – Mississippi',
								'MO' => 'MO – Missouri',
								'MT' => 'MT – Montana',
								'NE' => 'NE – Nebraska',
								'NV' => 'NV – Nevada',
								'NH' => 'NH – New Hampshire',
								'NJ' => 'NJ – New Jersey',
								'NM' => 'NM – New Mexico',
								'NY' => 'NY – New York',
								'NC' => 'NC – North Carolina',
								'ND' => 'ND – North Dakota',
								'OH' => 'OH – Ohio',
								'OK' => 'OK – Oklahoma',
								'OR' => 'OR – Oregon',
								'PA' => 'PA – Pennsylvania',
								'RI' => 'RI – Rhode Island',
								'SC' => 'SC – South Carolina',
								'SD' => 'SD – South Dakota',
								'TN' => 'TN – Tennessee',
								'TX' => 'TX – Texas',
								'UT' => 'UT – Utah',
								'VT' => 'VT – Vermont',
								'VA' => 'VA – Virginia',
								'WA' => 'WA – Washington',
								'WV' => 'WV – West Virginia',
								'WI' => 'WI – Wisconsin',
								'WY' => 'WY – Wyoming',
							),
							'default_value'     => array(),
							'allow_null'        => 1,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_5c6b43d523486',
							'label'             => 'State / Province',
							'name'              => 'state_province',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6aebcc8b65f',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b43d523487',
							'label'             => 'Zip Code',
							'name'              => 'zip_code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '25',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b43d523488',
							'label'             => 'Country',
							'name'              => 'country',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6aebcc8b65f',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5c6b427b0ce02',
					'label'             => 'Communication',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5c6e9dab848c7',
					'label'             => 'Recent Entries',
					'name'              => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'new_lines'         => '',
					'esc_html'          => 0,
				),
				array(
					'key'               => 'field_5c6b43a73f2cb',
					'label'             => 'Notes',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5c6aebcc8b685',
					'label'             => '',
					'name'              => 'notes',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '100',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'visual',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'contact',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c18368a47ad6',
			'title'                 => 'Event Details',
			'fields'                => array(
				array(
					'key'               => 'field_5c890d14798da',
					'label'             => 'General',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5c6da8270d3c5',
					'label'             => 'Primary Contact',
					'name'              => 'primary_event_contact',
					'type'              => 'post_object',
					'instructions'      => 'Select an organizer for this event',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33.3333',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'contact',
					),
					'taxonomy'          => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'return_format'     => 'object',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_5c6dabdb48b42',
					'label'             => 'Location',
					'name'              => 'event_organization',
					'type'              => 'post_object',
					'instructions'      => 'Select an organization for this event',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33.3333',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'organization',
					),
					'taxonomy'          => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'return_format'     => 'object',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_5c6db8e390f94',
					'label'             => 'Event Display Settings',
					'name'              => 'event_display_settings',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33.3333',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'public'   => 'Show all event details publicly',
						'pending'  => 'Hide event details and mark as "Pending"',
						'personal' => 'Hide event details and mark as "Unavailable"',
					),
					'allow_null'        => 0,
					'other_choice'      => 0,
					'default_value'     => 'public',
					'layout'            => 'vertical',
					'return_format'     => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key'               => 'field_5c6daa73990cc',
					'label'             => 'Public Details',
					'name'              => 'public_details',
					'type'              => 'group',
					'instructions'      => 'Enter details to display on the public event page',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '40',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c18ffaa50a55',
							'label'             => 'More Information',
							'name'              => 'more_info',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'tabs'              => 'visual',
							'toolbar'           => 'basic',
							'media_upload'      => 0,
							'delay'             => 0,
						),
						array(
							'key'               => 'field_5c18fd632f82c',
							'label'             => 'Website',
							'name'              => 'event_website',
							'type'              => 'url',
							'instructions'      => 'Enter the website dedicated to this event if one exists',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
						),
					),
				),
				array(
					'key'               => 'field_5c18fd7d2f82d',
					'label'             => 'Private Details',
					'name'              => 'private_details',
					'type'              => 'group',
					'instructions'      => 'Enter details for your private records. This information is always private.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '60',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c196ffbd0197',
							'label'             => 'Communication',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'top',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_5c6dbe661386b',
							'label'             => 'Recent Entries',
							'name'              => '',
							'type'              => 'message',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'new_lines'         => '',
							'esc_html'          => 0,
						),
						array(
							'key'               => 'field_5c196de37c9f1',
							'label'             => 'Ministry',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'top',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_5c18fe8d2f831',
							'label'             => 'Preaching Responsibilities',
							'name'              => 'preaching',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '100',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'Preaching all day Sunday and Mon-Fri at 7:00',
							'maxlength'         => '',
							'rows'              => 5,
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_5c190331df386',
							'label'             => 'Special Music',
							'name'              => 'special_music',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '100',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'Specials in the AM and PM services',
							'maxlength'         => '',
							'rows'              => 5,
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_5c1902acade49',
							'label'             => 'Children\'s Meetings',
							'name'              => 'childrens_meetings',
							'type'              => 'radio',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'yes' => 'Yes',
								'no'  => 'No',
							),
							'allow_null'        => 0,
							'other_choice'      => 1,
							'save_other_choice' => 0,
							'default_value'     => '',
							'layout'            => 'vertical',
							'return_format'     => 'value',
						),
						array(
							'key'               => 'field_5c1980c3dcc68',
							'label'             => 'Book Table',
							'name'              => 'book_table',
							'type'              => 'radio',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Yes' => 'Yes',
								'No'  => 'No',
							),
							'allow_null'        => 0,
							'other_choice'      => 1,
							'save_other_choice' => 0,
							'default_value'     => '',
							'layout'            => 'vertical',
							'return_format'     => 'value',
						),
						array(
							'key'               => 'field_5c6db0e750770',
							'label'             => 'Lodging',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'top',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_5c6db16a13c29',
							'label'             => 'We are staying in...',
							'name'              => 'staying_in',
							'type'              => 'radio',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '45',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'rv'               => 'RV',
								'prophets_chamber' => 'Prophets Chamber',
								'missionary_house' => 'Missionary House',
							),
							'allow_null'        => 0,
							'other_choice'      => 1,
							'save_other_choice' => 0,
							'default_value'     => '',
							'layout'            => 'vertical',
							'return_format'     => 'label',
						),
						array(
							'key'               => 'field_5c6db19286ce5',
							'label'             => 'Notes',
							'name'              => 'lodging_notes',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '55',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'Staying in a home with 13 cats.',
							'maxlength'         => '',
							'rows'              => 6,
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_5c196ce098d8c',
							'label'             => 'Travel',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'top',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_5c197304ff66c',
							'label'             => 'Estimated Travel Time',
							'name'              => 'estimated_travel_time',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '80',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => 'We will be traveling for',
							'append'            => 'hours',
							'min'               => '',
							'max'               => '',
							'step'              => '.25',
						),
						array(
							'key'               => 'field_5c18fd8d2f82e',
							'label'             => '',
							'name'              => 'travel_plans',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'Arrive by 5:00 PM on Saturday for dinner with pastor',
							'maxlength'         => '',
							'rows'              => 5,
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_5c890d3d798db',
							'label'             => 'Notes',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'top',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_5c895e1f51b67',
							'label'             => '',
							'name'              => 'notes',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'tabs'              => 'visual',
							'toolbar'           => 'basic',
							'media_upload'      => 0,
							'delay'             => 0,
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'event',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c6b29ef6b202',
			'title'                 => 'Organization Details',
			'fields'                => array(
				array(
					'key'               => 'field_5c6b29ef6e7a4',
					'label'             => 'General',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5c6b29ef6e719',
					'label'             => 'Main Phone',
					'name'              => 'main_phone',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5c6b29ef6e761',
					'label'             => 'Main Email',
					'name'              => 'main_email',
					'type'              => 'email',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_5c6b29ef6e779',
					'label'             => 'Website',
					'name'              => 'website',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5c6b29ef6e786',
					'label'             => 'Is this organization outside of the United States?',
					'name'              => 'international_address_question',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'no'  => 'No',
						'yes' => 'Yes',
					),
					'allow_null'        => 0,
					'other_choice'      => 0,
					'default_value'     => 'no',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key'               => 'field_5c6b29ef6e78f',
					'label'             => 'Physical Address',
					'name'              => 'physical_address',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c6b29ef76479',
							'label'             => 'Street',
							'name'              => 'street',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '100',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef76493',
							'label'             => 'City',
							'name'              => 'city',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '40',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef764a1',
							'label'             => 'State',
							'name'              => 'state',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6b29ef6e786',
										'operator' => '==',
										'value'    => 'no',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'AL' => 'AL – Alabama',
								'AK' => 'AK – Alaska',
								'AZ' => 'AZ – Arizona',
								'AR' => 'AR – Arkansas',
								'CA' => 'CA – California',
								'CO' => 'CO – Colorado',
								'CT' => 'CT – Connecticut',
								'DE' => 'DE – Delaware',
								'FL' => 'FL – Florida',
								'GA' => 'GA – Georgia',
								'HI' => 'HI – Hawaii',
								'ID' => 'ID – Idaho',
								'IL' => 'IL – Illinois',
								'IN' => 'IN – Indiana',
								'IA' => 'IA – Iowa',
								'KS' => 'KS – Kansas',
								'KY' => 'KY – Kentucky',
								'LA' => 'LA – Louisiana',
								'ME' => 'ME – Maine',
								'MD' => 'MD – Maryland',
								'MA' => 'MA – Massachusetts',
								'MI' => 'MI – Michigan',
								'MN' => 'MN – Minnesota',
								'MS' => 'MS – Mississippi',
								'MO' => 'MO – Missouri',
								'MT' => 'MT – Montana',
								'NE' => 'NE – Nebraska',
								'NV' => 'NV – Nevada',
								'NH' => 'NH – New Hampshire',
								'NJ' => 'NJ – New Jersey',
								'NM' => 'NM – New Mexico',
								'NY' => 'NY – New York',
								'NC' => 'NC – North Carolina',
								'ND' => 'ND – North Dakota',
								'OH' => 'OH – Ohio',
								'OK' => 'OK – Oklahoma',
								'OR' => 'OR – Oregon',
								'PA' => 'PA – Pennsylvania',
								'RI' => 'RI – Rhode Island',
								'SC' => 'SC – South Carolina',
								'SD' => 'SD – South Dakota',
								'TN' => 'TN – Tennessee',
								'TX' => 'TX – Texas',
								'UT' => 'UT – Utah',
								'VT' => 'VT – Vermont',
								'VA' => 'VA – Virginia',
								'WA' => 'WA – Washington',
								'WV' => 'WV – West Virginia',
								'WI' => 'WI – Wisconsin',
								'WY' => 'WY – Wyoming',
							),
							'default_value'     => array(),
							'allow_null'        => 1,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_5c6b29ef764ae',
							'label'             => 'State / Province',
							'name'              => 'state_province',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6b29ef6e786',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef764c1',
							'label'             => 'Zip Code',
							'name'              => 'zip_code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '25',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef764e8',
							'label'             => 'Country',
							'name'              => 'country',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6b29ef6e786',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5c6b29ef6e79a',
					'label'             => 'Mailing Address',
					'name'              => 'mailing_address',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5c6b29ef7f3d0',
							'label'             => 'Street',
							'name'              => 'street',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '100',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef7f3f4',
							'label'             => 'City',
							'name'              => 'city',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '40',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef7f400',
							'label'             => 'State',
							'name'              => 'state',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6b29ef6e786',
										'operator' => '==',
										'value'    => 'no',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'AL' => 'AL – Alabama',
								'AK' => 'AK – Alaska',
								'AZ' => 'AZ – Arizona',
								'AR' => 'AR – Arkansas',
								'CA' => 'CA – California',
								'CO' => 'CO – Colorado',
								'CT' => 'CT – Connecticut',
								'DE' => 'DE – Delaware',
								'FL' => 'FL – Florida',
								'GA' => 'GA – Georgia',
								'HI' => 'HI – Hawaii',
								'ID' => 'ID – Idaho',
								'IL' => 'IL – Illinois',
								'IN' => 'IN – Indiana',
								'IA' => 'IA – Iowa',
								'KS' => 'KS – Kansas',
								'KY' => 'KY – Kentucky',
								'LA' => 'LA – Louisiana',
								'ME' => 'ME – Maine',
								'MD' => 'MD – Maryland',
								'MA' => 'MA – Massachusetts',
								'MI' => 'MI – Michigan',
								'MN' => 'MN – Minnesota',
								'MS' => 'MS – Mississippi',
								'MO' => 'MO – Missouri',
								'MT' => 'MT – Montana',
								'NE' => 'NE – Nebraska',
								'NV' => 'NV – Nevada',
								'NH' => 'NH – New Hampshire',
								'NJ' => 'NJ – New Jersey',
								'NM' => 'NM – New Mexico',
								'NY' => 'NY – New York',
								'NC' => 'NC – North Carolina',
								'ND' => 'ND – North Dakota',
								'OH' => 'OH – Ohio',
								'OK' => 'OK – Oklahoma',
								'OR' => 'OR – Oregon',
								'PA' => 'PA – Pennsylvania',
								'RI' => 'RI – Rhode Island',
								'SC' => 'SC – South Carolina',
								'SD' => 'SD – South Dakota',
								'TN' => 'TN – Tennessee',
								'TX' => 'TX – Texas',
								'UT' => 'UT – Utah',
								'VT' => 'VT – Vermont',
								'VA' => 'VA – Virginia',
								'WA' => 'WA – Washington',
								'WV' => 'WV – West Virginia',
								'WI' => 'WI – Wisconsin',
								'WY' => 'WY – Wyoming',
							),
							'default_value'     => array(),
							'allow_null'        => 1,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_5c6b29ef7f40c',
							'label'             => 'State / Province',
							'name'              => 'state_province',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6b29ef6e786',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '35',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef7f418',
							'label'             => 'Zip Code',
							'name'              => 'zip_code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '25',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5c6b29ef7f423',
							'label'             => 'Country',
							'name'              => 'country',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5c6b29ef6e786',
										'operator' => '==',
										'value'    => 'yes',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5c6b29ef6e7bd',
					'label'             => 'Lodging',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5c6b29ef6e7d1',
					'label'             => 'Facilities',
					'name'              => 'facilities',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'rv'               => 'RV',
						'prophets_chamber' => 'Prophets Chamber',
						'missionary_house' => 'Missionary House',
					),
					'allow_custom'      => 0,
					'default_value'     => array(),
					'layout'            => 'horizontal',
					'toggle'            => 0,
					'return_format'     => 'label',
					'save_custom'       => 0,
				),
				array(
					'key'               => 'field_5c6b29ef6e7e4',
					'label'             => 'Hookups',
					'name'              => 'hookups',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5c6b29ef6e7d1',
								'operator' => '==',
								'value'    => 'rv',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'50-amp' => '50 amp',
						'30-amp' => '30 amp',
						'water'  => 'Water',
						'sewer'  => 'Sewer',
					),
					'allow_custom'      => 0,
					'default_value'     => array(
						0 => '50-amp',
						1 => 'water',
					),
					'layout'            => 'horizontal',
					'toggle'            => 0,
					'return_format'     => 'label',
					'save_custom'       => 0,
				),
				array(
					'key'               => 'field_5c6b29ef6e7ed',
					'label'             => 'Notes',
					'name'              => 'lodging_notes',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_5c6b29ef6e85e',
					'label'             => 'Notes',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_5c6b29ef6e867',
					'label'             => '',
					'name'              => 'notes',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'visual',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 0,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'organization',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	endif;
